apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: pydio-cells
version: 7.0.5
appVersion: "4.0.4"
description: Pydio-cells is the nextgen file sharing platform for organizations.
type: application
deprecated: false
home: https://truecharts.org/docs/charts/stable/pydio-cells
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pydio-cells.png
keywords:
  - pydio-cells
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/pydio-cells
  - https://hub.docker.com/r/linuxserver/pydio-cells
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.0.3
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.truecharts.org/
    version: 5.0.4
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - incubator
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
