name: "SCALE: catalog-tests"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      chartChangesDetected:
        required: true
        type: string

jobs:
  catalog-tests:
    name: Test SCALE Catalog
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truecharts/devcontainer:3.0.0@sha256:49b51eaada54ba2a1f217562647d018a8ddf0b9209f4bd2fabf96ead83bb9514
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
        name: Checkout
        with:
          fetch-depth: 100
          ref: ${{ inputs.checkoutCommit }}

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
        with:
          repository: truecharts/catalog
          path: catalog

      - name: build-and-run
        run: |
          tools/build-release.sh

      - uses: vishnudxb/cancel-workflow@c3c77eb4383ba7d023e6614a07d94fe990501ac6 # tag=v1.2
        if: failure()
        with:
          repo: truecharts/charts
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}
